config/routes.rb
Prize::Application.routes.draw do

  devise_for :users

  resources :users, :only => [] do
    resources :user_activity, :as => :events, :only => [:show]
  end

  resources :user_activity, :as => :events, :only => [:index]

  resources :comments, :only => [:create, :index]
  resources :likes, :only => [:create]

  resources :categories, :only => [:index] do
    resources :pictures, :only => [:index, :show]
  end

  get :show_all_pictures, :to => "pictures#show_all"
  root :to => 'categories#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
  belongs_to :user

  validates :user_email, :body, :presence => true

  after_create :add_act

  protected
  def add_act
    UserActivity.create(
        :user_id => user_id,
        :data_type => UserActivity::ACTIVITY_TYPES['comments'],
        :info => {:id => picture_id, :text => body}
    )
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :picture, :counter_cache => :likes_count

  validates :user_id, :picture_id, :numericality => true, :presence => true, :if => :not_new

  def not_new
    !new_record?
  end

  after_create :add_act

  protected
  def add_act
    UserActivity.create(
        :user_id => user_id,
        :data_type => UserActivity::ACTIVITY_TYPES['likes'],
        :info => {:id => picture_id}
    )
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :picture, :styles => {:big => "512x512",:normal => "256x256",:thumb => "128x128>" }
  has_many :comments, :dependent => :destroy
  has_many :users, :through => :likes
  has_many :likes, :dependent => :destroy
  belongs_to :picture_category

  validates :picture_category_id, :numericality => true, :presence => true, :if => :new_record?
end

app/models/picture_category.rb
class PictureCategory < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy

  validates :title, :presence => true, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :lockable, :timeoutable and :omniauthable , :validatable, :confirmable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :pictures, :through => :likes
  has_many :likes
  has_many :comments
  has_many :user_activities, :dependent => :destroy

  validates :email, :uniqueness => {:case_sensitive => false}, :format => {:with => Devise.email_regexp}
  validates :email, :password, :password_confirmation, :presence => true, :length => {:minimum => 3, :maximum => 60}

  def add_sign_in_act
    add_act 'user_sign_in'
  end

  def add_sign_out_act
    add_act 'user_sign_out'
  end

  protected
  def add_act type
    UserActivity.create(
        :user_id => id,
        :data_type => UserActivity::ACTIVITY_TYPES[type],
        :info => {:time => DateTime.now}
    )
  end
end

app/models/user_activity.rb
class UserActivity < ActiveRecord::Base
  ACTIVITY_TYPES = { 'navigation' => 0, 'user_sign_in' => 1, 'user_sign_out' => 2, 'likes' => 3, 'comments' => 4 }

  serialize :info, Hash
  belongs_to :user

  validates :data_type, :uniqueness => {:scope => [:user_id, :created_at]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  before_filter :add_user_action

  def after_sign_in_path_for(resource)
  	:root || stored_location_for(resource) || welcome_path
  end

  def add_user_action
    @user = current_user
    @user.user_activities.create(
        :data_type => UserActivity::ACTIVITY_TYPES['navigation'],
        :info => {:path => request.fullpath, :type => request.method}
    ) if user_signed_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @picture_categories = PictureCategory.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = @user.comments.create(params[:comment])
    render :json => {:status => !comment.new_record?, :create_time => comment.created_at}
  end

  def index
    @comments = Comment.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    render :json => {:status => !@user.likes.create(params[:like]).new_record?}
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.joins(:picture_category).where("picture_categories.title = ?", params[:category_id]).paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @picture = Picture.includes(:comments).find_by_id(params[:picture_id])
    @current_user_like = @picture.likes_count == 0 ? false : !@user.likes.find_by_picture_id(params[:picture_id]).blank?
  end

  def show_all
    @pictures = Picture.order("likes_count DESC").paginate(:page => params[:page], :per_page => 5)
    @size = :thumb
    render :action => :index
  end
end

app/controllers/user_activity_controller.rb
class UserActivityController < ApplicationController
  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @user_id = params[:user_id]
    @activities = UserActivity.where(:user_id => @user_id, :data_type => UserActivity::ACTIVITY_TYPES[params[:id]]).paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_activity_helper.rb
module UserActivityHelper
  def message(activity)
    case activity.data_type
      when 0
        "go to (#{activity.info[:type]}) #{activity.info[:path]}"
      when 1
        "sign in at #{activity.info[:time]}"
      when 2
        "sign out at #{activity.info[:time]}"
      when 3
        "set like for picture with id #{activity.info[:id]}"
      when 4
        "set comment '#{activity.info[:text]}' for picture with id #{activity.info[:id]}"
      else
        'Unrecognized type'
    end
  end
end

app/views/categories/index.html.haml
.secondary-navigation
  %ul.wat-cf
    - @picture_categories.each do |category|
      %li= link_to category.title, category_pictures_path(category.title)

app/views/comments/index.html.haml
#comments
  %table
    - @comments.each do |comment|
      %tr
        %td= time_ago_in_words(comment.created_at)
        %td= image_tag comment.picture.picture.url(:thumb)
        %td= comment.user_email
        %td= comment.body

= will_paginate @comments
%br
%br

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Web App
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} '(O_o)'
        #user-navigation
          %ul.wat-cf
            - if user_signed_in?
              %li
                %a.logout{:href => destroy_user_session_path, 'data-method' => :delete}= t("logout", :default => "Logout")
            - else
              %li
                %a{:href => new_user_registration_path }= t("registration", :default => "Registration")
              %li
                %a{:href => new_user_session_path }= t("authorization", :default => "Authorization")
        #main-navigation
          %ul.wat-cf
            %li= link_to 'Picture categories', categories_path
            %li= link_to 'All pictures', show_all_pictures_path
            %li= link_to 'Comments', comments_path
            %li= link_to 'User actions', events_path

      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield

        #sidebar
          = yield :sidebar
      #footer
        .block
          %p{:style => "text-align: center;"}
            Copyright &copy; #{Time.now.year} Web App.

app/views/pictures/index.html.haml
-if @pictures
  #pictures
    - @pictures.each do |picture|
      %picture
        = link_to image_tag(picture.picture.url(@size || :normal)), category_picture_path(picture.picture_category.title, picture.id)
        = picture.likes_count

  = will_paginate @pictures
  %br
  %br

app/views/pictures/show.html.haml
#picture
  = image_tag(@picture.picture.url(:big))
#like
  %span Likes
  %span.likes_count= @picture.likes_count
  - unless @current_user_like
    %span.set_like
      = link_to image_tag('LikeButton.gif', :size => "45x25"), "#", :onclick => "setLike('#{likes_create_path}', '#{@picture.id}');"
  - else
    %span You already set like for this picture
%br
#comments
  - @picture.comments.each do |comment|
    .comment
      .name= comment.user_email
      .comment_time= comment.created_at
      .clear
      .comment_body= comment.body
    %br

#add_comment
  = form_for :comment, :html =>{ :remote => true } do |f|
    = f.text_area :body, :cols => 40, :rows => 5
    = f.submit :Comment, :onclick => "sendComment('#{comments_path}', '#{@picture.id}', '#{@user.email}', jQuery('#comment_body').attr('value')); return false;"

app/views/user_activity/_acts.html.haml
- UserActivity::ACTIVITY_TYPES.each do |type|
  = link_to type.first.humanize, user_event_path(user_id, type.first), :style => "padding-right : 10px;"

app/views/user_activity/index.html.haml
#users_with_activities
  %table
    %tr
      %th User
      %th Acts

    - @users.each do |user|
      %tr
        %td{:style => user == @user ? "color:red; font-weight: bold;" : ""}= user.email
        %td{:style => "padding-left : 10px;"}
          = render :partial => 'acts', :locals => {:user_id => user.id}

app/views/user_activity/show.html.haml
#activity_menu
  = render :partial => 'acts', :locals => {:user_id => @user_id}
  %br
  %br

#activities
  - @activities.each do |activity|
    .activity
      %strong{:style => "padding-right : 10px;"}= activity.created_at
      %span= message(activity)
    %br

= will_paginate @activities
%br
%br